source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'puma', '~> 5.3.2', require: false

gem 'roda', '~> 3.43.0'

gem 'isomorfeus-puppetmaster', '>= 0.4.0'

gem 'rspec'

gem 'opal', github: 'janbiedermann/opal', branch: 'es6_modules_1_2'
gem 'opal-webpack-loader', '>= 0.11.0'

