source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'puma', '~> 5.3.0', require: false

gem 'roda', '~> 3.43.0'

gem 'isomorfeus-puppetmaster', '>= 0.4.0'

gem 'rspec'
